### ISSUE TITLE
Passing token for every request

### ISSUE THREAD

**Issue by varukashotta** [supercycle91/graphql-microservices-example#2]
Hello, Thank you for the tutorial

I would like to know how i can pass a header authorisation variable to every graphql request 

Thank you

**Comment by david-novicki** [comment]
@varukashotta Please check out my response [here](https://medium.com/@varuka/thank-you-for-the-tutorial-would-you-know-how-to-add-bearer-tokens-to-specific-endpoints-before-172910d86487)
